### ISSUE TITLE
DIR reporting incorrect file size

### ISSUE THREAD

**Issue by MackW** [RevCurtisP/AquariusPlus#6]
Dir for some files gives incorrect sizes - example in net folder for telnet.aqx
![456670307_1227313578422965_2614410283034658821_n](https://github.com/user-attachments/assets/0daa9b73-d984-4616-9156-7bbe22b4fa46)

**Comment by RevCurtisP** [comment]
Fixed in v0.23b

**Comment by RevCurtisP** [comment]
Fixed in v0.23b
